blueprint:
  name: Advanced Custom Motion Sensor Enhanced (No Brightness Override)
  description: |
    Automação de movimento com controle por luminosidade, horário e sol.
    Use Brightness Level = -1 para NÃO alterar o brilho atual da lâmpada.

  domain: automation
  source_url: https://github.com/arturoliveira/home-assistant/blob/main/advanced_custom_motion_sensor.yaml

  input:
    motion_entity:
      name: Motion Sensor(s)
      selector:
        entity:
          multiple: true

    light_target:
      name: Light(s)
      selector:
        target:
          entity:
            domain: light

    luminance_sensor:
      name: Illuminance sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    luminance_required:
      name: Required Lux Level
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lx

    no_motion_wait:
      name: Wait time after no motion
      default: 120
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds

    brightness_level:
      name: Brightness Level (%)
      description: Use -1 para NÃO alterar o brilho da lâmpada
      default: -1
      selector:
        number:
          min: -1
          max: 100
          unit_of_measurement: "%"
          step: 1

    time_default_start:
      name: Only run after time
      default: "00:00:00"
      selector:
        time: {}

    time_default_end:
      name: Only run before time
      default: "23:59:59"
      selector:
        time: {}

    elevation:
      name: Sun elevation condition
      default: Always
      selector:
        select:
          options:
            - Always
            - Below horizon
            - Above horizon

    elevation_adjustment:
      name: Sun elevation adjustment
      default: 0
      selector:
        number:
          min: -90
          max: 90
          unit_of_measurement: degrees

    automation_blocker_entities:
      name: Automation Blocker Entities
      default: []
      selector:
        entity:
          multiple: true

    automation_blocker_boolean:
      name: Automation Blocker Desired State
      default: false
      selector:
        boolean: {}

    motion_off_blocker:
      name: Motion Off Blocker Entities
      default: []
      selector:
        entity:
          multiple: true

    motion_off_blocker_boolean:
      name: Motion Off Blocker Desired State
      default: false
      selector:
        boolean: {}

    scene_ambient:
      name: Ambient Scene
      default: scene.none
      selector:
        entity:
          domain: scene

    time_scene_ambient_start:
      name: Ambient Scene St
